### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by ostrokach** [akiyamalab/MEGADOCK#22]
Currently, this project appears to be licensed under the ["Apache-2.0" license](https://github.com/akiyamalab/MEGADOCK/blob/master/LICENSE), which allows commercial work.

However, in your README, you state that "This software and derivatives are NOT allowed for any commercial use without formal prior authorization."

Could you clarify this discrepancy? If the README is correct, I think the LICENSE file should be adjusted accordingly and should no longer be "Apache-2.0".

(thanks for the great project, btw :))

**Comment by biochem-fan** [comment]
Moreover, Apache 2.0 license is incompatible with linking to FFTW (GPL).

**Comment by biochem-fan** [comment]
FYI: https://twitter.com/eriklindahl/status/1539570970423328769
