### ISSUE TITLE
compiling MEGADOCK for anything other than CPU & single node

### ISSUE THREAD

**Issue by ponomarevsy** [akiyamalab/MEGADOCK#23]
Hello!

I've tested all four different compilations (gpu, gpu-mpi, cpu-mpi, cpu) but keep getting the CPU & single node version only, it seems (file sizes of executables are all the same). The "megadock-gpu" executable is not produced, but rather, the "megadock" file is being created. I use "make clean" and/or "make allclean" (I copy the executable into a bin folder first) before running a different compilation.

```
» ls -lh                                                                                
total 23M
-rwxr-x--- 1 appbuild appbuild 2.9M Sep  7 11:20 megadock
-rwxr-x--- 1 appbuild appbuild 2.9M Sep  7 11:22 megadock-gpu
-rwxr-x--- 1 appbuild appbuild 2.9M Sep  7 11:06 megadock-gpu-mpi
-rwxr-x--- 1 appbuild appbuild 2.9M Sep  7 11:09 megadock-mpi
```

These are parameters I change:

```
» more Makefile                                                                                                  
#############################################################
# Compile options start                                     #
#-----------------------------------------------------------#
#                                                           #

#----------------------------------------------#
# Library PATH and compiler settings           #
#----------------------------------------------#

CUDA_INSTALL_PATH ?= /sysapps/cluster/software/CUDA/10.0.130-GCC-4.8.4
CUDA_SAMPLES_PATH ?= /sysapps/cluster/software/CUDA/10.0.130-GCC-4.8.4/samples
FFTW_INSTALL_PATH ?= /sysapps/cluster/software/FFTW/3.3.4-gompi-1.7.20
CPPCOMPILER       ?= g++
#MPICOMPILER       ?= mpicxx
OPTIMIZATION      ?= -O3
OMPFLAG           ?= -fopenmp
 # (If you use g++ compiler, please set the value as "-fopenmp".)

#----------------------------------------------#
# Environment settings                         #
#----------------------------------------------#

USE_GPU    := 1
 # (If you do not use GPU, please set the value as 0 or comment out of the line.)

USE_MPI    := 0
 # (If you do not use MPI, please set the value as 0 or comment out of the line.)

#                                                           #
#-----------------------------------------------------------#
# Compile options end                                       #
...
```

```
» ./megadock-mpi                                                                          
 MEGADOCK ver. 4.1.3 for CPU & single node
      megadock@bi.c.titech.ac.jp   lastupdated: 26 March, 2019

# Using OpenMP parallelization: 56 threads.
[ERROR] Receptor PDB file is not assignment!!

 Usage: megadock -R [receptor.pdb] -L [ligand.pdb] [more options]
...
```

```
» ./megadock-gpu-mpi                                                                                         
 MEGADOCK ver. 4.1.3 for CPU & single node
      megadock@bi.c.titech.ac.jp   lastupdated: 26 March, 2019

# Using OpenMP parallelization: 56 threads.
[ERROR] Receptor PDB file is not assignment!!

 Usage: megadock -R [receptor.pdb] -L [ligand.pdb] [more options]
...
```

```
» ./megadock-gpu                                                                         
 MEGADOCK ver. 4.1.3 for CPU & single node
      megadock@bi.c.titech.ac.jp   lastupdated: 26 March, 2019

# Using OpenMP parallelization: 56 threads.
[ERROR] Receptor PDB file is not assignment!!

 Usage: megadock -R [receptor.pdb] -L [ligand.pdb] [more options]
...
```

```
./megadock                                                                                           
 MEGADOCK ver. 4.1.3 for CPU & single node
      megadock@bi.c.titech.ac.jp   lastupdated: 26 March, 2019

# Using OpenMP parallelization: 56 threads.
[ERROR] Receptor PDB file is not assignment!!

 Usage: megadock -R [receptor.pdb] -L [ligand.pdb] [more options]
...
```

Please advice how to proceed. Thank you!

**Comment by metaVariable** [comment]
Hi, @ponomarevsy!

I tested the compilation flags for CPU/GPU variants using the latest release (4.1.3) and checked generated binaries, but it seemed to work fine for our environment.

```s
> ./megadock
 MEGADOCK ver. 4.1.3 for CPU & single node
      megadock@bi.c.titech.ac.jp   lastupdated: 26 March, 2019

# Using OpenMP parallelization: 56 threads.
```
```s
> ./megadock-gpu
 MEGADOCK ver. 4.1.3 for GPU & single node
      megadock@bi.c.titech.ac.jp   lastupdated: 26 March, 2019

# Using OpenMP parallelization: 56 threads.
# Using CUDA device 0: Tesla P100-SXM2-16GB
# CUFFT version : 10400
# Number of available [threads / GPUs] : [56 / 4]
```

Could you possibly share the executed copying commands and compilation logs (exclude MPI variants) here?

Thanks for testing MEGADOCK on your cluster environment.

**Comment by ponomarevsy** [comment]
Hi @metaVariable,

So, here is what I have: 

the GitHub (clone) produces only megadock CPU & single node no matter what options I choose, but,
the GitHub (zip) compiles everything correctly.

Compilation options do NOT work (megadock CPU & single node for all 4 case): 
```
# from GitHub (clone)
git clone https://github.com/akiyamalab/MEGADOCK.git
cd MEGADOCK
```

Compilation options work fine for me: 
```
# from GitHub (zip)
wget https://github.com/akiyamalab/MEGADOCK/archive/master.zip
unzip master.zip
cd MEGADOCK-master
```

**Comment by metaVariable** [comment]
Hi @ponomarevsy,

I've tried to reproduce the current issue, but unfortunately, I cannot catch the same case with testing the latest git repo (master) for combinations of CPU/GPU and MPI variants.

'MPICOMPILER' in Makefile may possibly be a cause of this issue.
But if the 'MPICOMPILER' is missing then the compilation should be failed for MPI variants.

We usually give it as a command in PATH, however, giving a clear path to the variables may clarify the cause, as you mention.
```Makefile
MPICOMPILER       ?= mpicxx
```

And, if the MPI options are enabled, the filename of generated binary is 'megadock-dp' or 'megadock-gpu-dp' by default.
Could you confirm the filenames of generated binaries before renaming them?
Then we can clarify the cause is whether Makefile or other. Thanks.

**Comment by ponomarevsy** [comment]
Should the original directory names be kept intact or can I rename them?

**MEGADOCK_GPU_MPI from GitHub (clone)**

```
#----------------------------------------------#
# Library PATH and compiler settings           #
#----------------------------------------------#

CUDA_INSTALL_PATH ?= /path/CUDA/10.0.130-GCC-4.8.4
CUDA_SAMPLES_PATH ?= /path/CUDA/10.0.130-GCC-4.8.4/samples
FFTW_INSTALL_PATH ?= /path/FFTW/3.3.4-gompi-1.7.20
CPPCOMPILER       ?= g++
MPICOMPILER       ?= mpicxx
OPTIMIZATION      ?= -O3
OMPFLAG           ?= -fopenmp
 # (If you use g++ compiler, please set the value as "-fopenmp".)

#----------------------------------------------#
# Environment settings                         #
#----------------------------------------------#

USE_GPU    := 1
 # (If you do not use GPU, please set the value as 0 or comment out of the line.)

USE_MPI    := 1
 # (If you do not use MPI, please set the value as 0 or comment out of the line.)

#                                                           #
#-----------------------------------------------------------#
```
» module list
Currently Loaded Modulefiles:
  1) EasyBuild/4.3.3            3) GCC/4.8.4                  5) hwloc/1.10.1-GCC-4.8.4     7) gompi/1.7.20               9) CUDA/10.0.130-GCC-4.8.4
  2) uge/8.6.15                 4) numactl/2.0.10-GCC-4.8.4   6) OpenMPI/1.8.4-GCC-4.8.4    8) FFTW/3.3.4-gompi-1.7.20

» make allclean

» make -j 12
--------------------------
make megadock start
--------------------------
mkdir -p obj_cs
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/control.cpp.o -c src/control.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/cpu_time.cpp.o -c src/cpu_time.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/docking.cpp.o -c src/docking.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/parameter.cpp.o -c src/parameter.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/pdb_entry.cpp.o -c src/pdb_entry.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/protein.cpp.o -c src/protein.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/receptor.cpp.o -c src/receptor.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/ligand.cpp.o -c src/ligand.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/fft_process.cpp.o -c src/fft_process.cpp
g++ -fopenmp -static  -O3 -Isrc -I/path/FFTW/3.3.4-gompi-1.7.20/include -o obj_cs/main.cpp.o -c src/main.cpp
g++ src/decoygen.cpp -lm -o decoygen
g++ src/calcrg.cpp -o calcrg
g++ -fPIC -fopenmp -o ./megadock obj_cs/control.cpp.o obj_cs/cpu_time.cpp.o obj_cs/docking.cpp.o obj_cs/parameter.cpp.o obj_cs/pdb_entry.cpp.o obj_cs/protein.cpp.o obj_cs/receptor.cpp.o obj_cs/ligand.cpp.o obj_cs/fft_process.cpp.o obj_cs/main.cpp.o  -lm -L/path/FFTW/3.3.4-gompi-1.7.20/lib -lfftw3f

This produces file "megadock":

```
» ls -lh 
total 5.9M
-rwxr-x--- 1 user user 1.6K Sep 13 10:52 block
-rwxr-x--- 1 user user  13K Sep 14 10:09 calcrg
drwxr-x--- 2 user user  512 Sep 13 10:52 data
-rwxr-x--- 1 user user  13K Sep 14 10:09 decoygen
drwxr-x--- 2 user user  512 Sep 13 10:52 doc
drwxr-x--- 5 user user  512 Sep 13 10:52 Dockerfiles
-rw-r----- 1 user user  12K Sep 13 10:52 LICENSE
-rw-r----- 1 user user 6.5K Sep 14 10:11 Makefile
-rw-r----- 1 user user 6.4K Sep 13 10:52 Makefile.old
-rwxr-x--- 1 user user 2.9M Sep 14 10:09 megadock
drwxr-x--- 2 user user  512 Sep 14 10:15 obj_cs
-rwxr-x--- 1 user user 2.2K Sep 13 10:52 ppiscore
-rw-r----- 1 user user 2.3K Sep 13 10:52 README.md
drwxr-x--- 2 user user 8.0K Sep 13 10:52 src
```

```
» ./megadock
 MEGADOCK ver. 4.1.3 for CPU & single node
      megadock@bi.c.titech.ac.jp   lastupdated: 26 March, 2019

# Using OpenMP parallelization: 56 threads.
[ERROR] Receptor PDB file is not assignment!!
```

**MEGADOCK-master_GPU_MPI from GitHub (clone)**

Makefile is the same as above except for explicit MPI library path in the 2nd case.

```
» diff Makefile ../MEGADOCK_GPU_MPI/Makefile                                                                  
14c14
< MPICOMPILER       ?= /path/OpenMPI/1.8.4-GCC-4.8.4/bin/mpicxx
---
> MPICOMPILER       ?= mpicxx
```
```
» make allclean

» make -j 12
```

Produces file "megadock-gpu":
```
» ls -l                                                                                                      
total 6192
-rwxr-x--- 1 user user    1627 Sep 13 11:06 block
-rwxr-x--- 1 user user   12936 Sep 14 10:25 calcrg
drwxr-x--- 2 user user     512 Sep 13 11:06 data
-rwxr-x--- 1 user user   13112 Sep 14 10:25 decoygen
drwxr-x--- 2 user user     512 Sep 13 11:06 doc
drwxr-x--- 5 user user     512 Sep 13 11:06 Dockerfiles
-rw-r----- 1 user user   11408 Sep 13 11:06 LICENSE
-rw-r----- 1 user user    6675 Sep 13 11:43 Makefile
-rw-r----- 1 user user    6513 Sep 13 11:06 Makefile.old
-rwxr-x--- 1 user user 3065256 Sep 14 10:25 megadock-gpu
drwxr-x--- 2 user user     512 Sep 14 10:25 obj_gs
-rwxr-x--- 1 user user    2247 Sep 13 11:06 ppiscore
-rw-r----- 1 user user    2305 Sep 13 11:06 README.md
drwxr-x--- 2 user user    8192 Sep 13 11:06 src
```

```
» which mpicxx                                                                                                
/path/OpenMPI/1.8.4-GCC-4.8.4/bin/mpicxx

» ./megadock-gpu                                                                                             
 MEGADOCK ver. 4.1.3 for GPU & single node
      megadock@bi.c.titech.ac.jp   lastupdated: 26 March, 2019

# Using OpenMP parallelization: 56 threads.
# Using CUDA device 0: Tesla V100-SXM2-32GB
# CUFFT version : 10000
# Number of available [threads / GPUs] : [56 / 8]
[ERROR] Receptor PDB file is not assignment!!
```

As you can see, I got myself completely confused...

**Comment by ponomarevsy** [comment]
I think I have the answer! There was a space after "1" in this line: 
```
USE_MPI    := 1 
```
As soon as I have removed the space, the MPI parameter was read correctly and the correct executable, "megadock-dp", was produced. 

So, the bottom line is, DO NOT use spaces after USE_GPU and USE_MPI definitions. Was this code written in Fortran?

**Comment by metaVariable** [comment]
I'm so glad to hear that! and, now I also reproduced the same case.
`USE_GPU` and `USE_MPI` flags seem to be ignored if the spaces exist at end of it.

Thanks for creating this issue, we would add some notes for the building documents.
